### ISSUE TITLE
Application crash while trying to update (null.appupdate.provider)

### ISSUE THREAD

**Issue by vaydich** [vaenow/cordova-plugin-app-update#149]
Hi, i've got following error after click on update:

```
03-24 15:46:50.804 12806 12939 E AndroidRuntime: FATAL EXCEPTION: JavaBridge
03-24 15:46:50.804 12806 12939 E AndroidRuntime: Process: io.ionic.starter, PID: 12806
03-24 15:46:50.804 12806 12939 E AndroidRuntime: java.lang.IllegalArgumentException: Couldn't find meta-data for provider with authority null.appupdate.provider
03-24 15:46:50.804 12806 12939 E AndroidRuntime:        at androidx.core.content.FileProvider.parsePathStrategy(FileProvider.java:662)
03-24 15:46:50.804 12806 12939 E AndroidRuntime:        at androidx.core.content.FileProvider.getPathStrategy(FileProvider.java:635)
03-24 15:46:50.804 12806 12939 E AndroidRuntime:        at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:441)
03-24 15:46:50.804 12806 12939 E AndroidRuntime:        at com.vaenow.appupdate.android.DownloadHandler.installApk(DownloadHandler.java:107)
03-24 15:46:50.804 12806 12939 E AndroidRuntime:        at com.vaenow.appupdate.android.DownloadHandler.handleMessage(DownloadHandler.java:60)
03-24 15:46:50.804 12806 12939 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
03-24 15:46:50.804 12806 12939 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
03-24 15:46:50.804 12806 12939 E AndroidRuntime:        at android.os.HandlerThread.run(HandlerThread.java:61) 
```

As i understood this line in DownloadHandler.java didn't work:

`String applicationId = (String) BuildHelper.getBuildConfigValue((Activity) mContext, "APPLICATION_ID");`

Any ideas what's the problem?

P.S.: String applicationId = mContext.getPackageName() can solve the problem?

**Comment by etplsg** [comment]
We faced the same problem and can confirm that mContext.getPackageName() works (it gives the applicationId)
